server:
  port: 8082

spring:
  application:
    name: finance-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/paynest_db?currentSchema=finance_schema}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: finance_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

paynest:
  jwt:
    secret: ${JWT_SECRET:b3BlbnNlc3NhbWUtc2VjcmV0LWNoYW5nZS1tZS1pbi1wcm9kdWN0aW9uLXBheW5lc3Q=}
    expiration: ${JWT_EXPIRATION:900000}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

logging:
  level:
    root: INFO
    com.paynest.financeservice: DEBUG
    org.hibernate.SQL: DEBUG
